version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=config.settings
    restart: unless-stopped
